# Generated by Django 5.2.3 on 2025-06-21 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=50)),
                ('servicios', models.CharField(max_length=150, null=True)),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('cantidad_habitaciones', models.IntegerField()),
                ('url_info', models.URLField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_personas', models.IntegerField()),
                ('descripcion', models.TextField(null=True)),
                ('estado', models.BooleanField()),
                ('hotel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='api.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de entrada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('cantidad_personas', models.IntegerField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.habitacion')),
            ],
        ),
    ]
